force-app/main/default/objects/Concierge_Live_Settings__c/Concierge_Live_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Settings for Concierge Live</description>
    <label>Concierge Live Settings</label>
</CustomObject>

force-app/main/default/objects/Concierge_Live_Settings__c/fields/Contact_Filter__c.field-meta.xml
<CustomField>
    <fullName>Contact_Filter__c</fullName>
    <description>SQL added to Contact-fetching to limit the results based on business rules of your organization about who can and cannot use assets in Concierge Live.</description>
    <label>Contact Filter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Concierge_Live_Settings__c/fields/Disallowed_Message__c.field-meta.xml
<CustomField>
    <fullName>Disallowed_Message__c</fullName>
    <description>Message to be shown when a chosen contact is not allowed by company policy.</description>
    <inlineHelpText>If you provided a Contact Filter above, you may optionally provide your own alert message when a disallowed contact is chosen from the search box.</inlineHelpText>
    <label>Contact Filter Disallowed Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Concierge_Live_Settings__c/fields/Manual_Select_Account_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Manual_Select_Account_Contacts__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When using the Account-level table, clicking &quot;Request Tickets&quot; will automatically select all Contacts for that Account. Enable this if you&apos;d like to manually choose Contacts one at a time.</description>
    <label>Manual Select Account Contacts?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Concierge_Live_Settings__c/fields/UseSandbox__c.field-meta.xml
<CustomField>
    <fullName>UseSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if you&apos;d like requests to go to conciergelive-staging.com instead of the main production site.</description>
    <label>Use Sandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ConciergeLiveConstants.cls
/**
* {Purpose} - Constants file
*
* @author
* @version
*/

/**
* CHANGE HISTORY
* =============================================================================
* Date          Name                    Description
*                                       Created
* =============================================================================
*/
public with sharing class ConciergeLiveConstants {

    public static final String APP_KEY                              = 'CONCIERGELIVE'; //Concierge Live
    public static final String CL_NAME                              = 'Concierge Live'; //Concierge Live
    public static final String APPLICATION_NAME                     = 'Concierge Live'; //Concierge Live

	public static final String EMAIL_SUPPORT_FOR_DEBUG				= 'dev@conciergelive.com';
	public static final String EMAIL_SUPPORT_FOR_DEBUG_SUBJECT		= 'Salesforce - Debug';
	public static final String EMAIL_SENDER_NAME_GENERIC 			= 'Salesforce';
    public static final String EMAIL_SENDER_GENERIC_REPLYTO         = 'dev@conciergelive.com';

    public static final String SUBMISSION_URL         				= 'https://[SUBDOMAIN].conciergelive.com/integrations/salesforce_calls/new';
    public static final String SUBMISSION_URL_SANDBOX         				= 'https://[SUBDOMAIN].conciergelive-staging.com/integrations/salesforce_calls/new';

    public static final String HISTORY_URL         					= 'https://[SUBDOMAIN].conciergelive.com/api/salesforce/contacts/[CONTACTID]/event_history';
    public static final String HISTORY_URL_SANDBOX         					= 'https://[SUBDOMAIN].conciergelive-staging.com/api/salesforce/contacts/[CONTACTID]/event_history';

    public static final String BULK_HISTORY_URL                     = 'https://[SUBDOMAIN].conciergelive.com/api/salesforce/contacts/event_history_bulk';
    public static final String BULK_HISTORY_URL_SANDBOX = 'https://[SUBDOMAIN].conciergelive-staging.com/api/salesforce/contacts/event_history_bulk';

    public static final String MESSAGE_NOHISTORY                    = 'No events found.';
    public static final String MESSAGE_GENERAL_ISSUE       			= 'We\'re having an issue completing your request.';
    public static final String MESSAGE_CALLOUT_FAILURE              = 'Concierge Live Event History is Unavailable at this time.';
    public static final String MESSAGE_MISSING_SUB_DOMAIN           = 'Please set the \'Sub Domain Name\' in Concierge Live Settings.';
    public static final String MESSAGE_MISSING_AUTHORIZATION_KEY	= 'Please set the \'Authorization Key\' in Concierge Live Settings.';

    @AuraEnabled(cacheable=true)
    public static String eventHistoryUrl() {
        Concierge_Live_Settings__c settings = ConciergeLiveUtils.getApplicationCustomSetting();
        if (settings.UseSandbox__c) {
            return HISTORY_URL_SANDBOX;
        }

        return HISTORY_URL;
    }

    @AuraEnabled(cacheable=true)
    public static String bulkEventHistoryUrl() {
        Concierge_Live_Settings__c settings = ConciergeLiveUtils.getApplicationCustomSetting();
        if (settings.UseSandbox__c) {
            return BULK_HISTORY_URL_SANDBOX;
        }

        return BULK_HISTORY_URL;
    }

    @AuraEnabled(cacheable=true)
    public static String submissionUrl() {
        Concierge_Live_Settings__c settings = ConciergeLiveUtils.getApplicationCustomSetting();
        if (settings.UseSandbox__c) {
            return SUBMISSION_URL_SANDBOX;
        }

        return SUBMISSION_URL;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean manualSelectAccountContacts() {
        Concierge_Live_Settings__c settings = ConciergeLiveUtils.getApplicationCustomSetting();
        return settings.Manual_Select_Account_Contacts__c;
    }

    @AuraEnabled(cacheable=true)
    public static String disallowedMessage() {
        Concierge_Live_Settings__c settings = ConciergeLiveUtils.getApplicationCustomSetting();
        String msg = settings.Disallowed_Message__c;

        if (msg != null && msg.length() > 0) {
            return msg;
        } else {
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static String contactFilterSql() {
        Concierge_Live_Settings__c settings = ConciergeLiveUtils.getApplicationCustomSetting();
        String contactFilter = settings.Contact_Filter__c;

        if (validContactFilter(contactFilter)) {
            return contactFilter;
        }

        return '';
    }

    // This is used to determine if a valid Contact Filter setting has been
    // provided. If the filter contains a semicolon, probably someone is trying
    // to do some SQL injection so just reject it outright.
    private static Boolean validContactFilter(String filterString) {
        return filterString != null &&
            filterString.length() > 0 &&
            filterString.split(';').size() == 1;
    }
}